app:
  name: 'KelasGo'
  version: '0.1.0'
  description: 'KelasGo API Service'
  url: 'http://localhost:8080'
  timezone: 'Asia/Jakarta'
  locale: 'en_US'
  pagination:
    default_limit: 10
    max_limit: 100
    enabled: true
  cors:
    allow_credentials: true
    allowed_headers: 'Accept,Authorization,Content-Type'
    allowed_methods: 'GET,PUT,POST,PATCH,DELETE,OPTIONS'
    allowed_origins: 'http://localhost:8080,http://127.0.0.1:8080'
    enabled: true
    max_age_seconds: 300

server:
  host: '0.0.0.0' # Bind to all interfaces to allow external access
  port: '8080'
  env: 'development'
  log_level: 'debug'
  shutdown:
    cleanup_period_seconds: 3
    grace_period_seconds: 3

jwt:
  secret: 'your-jwt-secret-key-change-in-production'

cache:
  redis:
    primary:
      host: 'localhost'
      port: 6379
      password: ''
      db: 1

db:
  pg:
    read:
      host: 'localhost'
      port: '5432'
      name: 'kelasgo'
      user: 'postgres'
      password: 'your_password_here'
      timezone: 'UTC'
      sslmode: 'disable'
      max_connection_lifetime: '5m'
      max_idle_connection: 10
      max_open_connection: 10
    write:
      host: 'localhost'
      port: '5432'
      name: 'kelasgo'
      user: 'postgres'
      password: 'your_password_here'
      timezone: 'UTC'
      sslmode: 'disable'
      max_connection_lifetime: '5m'
      max_idle_connection: 10
      max_open_connection: 10

encryption:
  key:
    users: '84c89d7d841947a5b6d4decc3215110c69ae587e3054'

external:
  s3:
    bucket_name: 'bucket_name_here'
    region: 'ap-southeast-1'
    base_url: 'url_here'
    access_key: 'access_key_here'
    secret: 'secret_here'

mail:
  host: 'smtp.gmail.com'
  port: 587
  username: 'your-email@gmail.com'
  password: 'your-app-password'
  workers: 5
